version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: yeoman-generator
    versions:
    - 4.12.0
    - 4.13.0
    - 5.0.0
    - 5.0.1
    - 5.1.0
  - dependency-name: yeoman-test
    versions:
    - 4.0.0
    - 4.0.1
    - 5.0.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
    - 4.7.7
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: acorn
    versions:
    - 5.7.4
